CodingExcrcise/Models/Coordinate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CodingExcrcise.Models
{
    public class Coordinate
    {
        [Display(Name = "Latitude")]
        public double Latitude { get; set; }

        [Display(Name = "Longitude")]
        public double Longitude { get; set; }
    }
}

CodingExcrcise/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CodingExcrcise.Models
{
    public class Location
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter city name")]
        [Display(Name = "City Name")]
        public string Name { get; set; }

        public Coordinate Coordinate { get; set; }
    }
}

CodingExcrcise/Models/Pollution.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CodingExcrcise.Models
{
    public class Pollution
    {
        [Display(Name = "Pollution Level")]
        string Level { get; set; }

        [Display(Name = "Air Quality Index")]
        int AQI { get; set; }

        [Display(Name = "City")]
        String City { get; set; }
    }
}

CodingExcrcise/Controllers/HomeController.cs
using CodingExcrcise.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodingExcrcise.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

CodingExcrcise/Controllers/LocationController.cs
using CodingExcrcise.Models;
using CodingExcrcise.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodingExcrcise.Controllers
{
    public class LocationController : Controller
    {
        private ILocationRepository locationRepository;

        public LocationController(ILocationRepository locationRepository)
        {
            this.locationRepository = locationRepository;
        }
        // GET: Location
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Pollution(Location model)
        {
            Pollution cp = new Pollution();
            try
            {
                cp = locationRepository.GetCityPolution(model, DateTime.Now);
                if (cp != null)
                    return View(cp);
            }
            catch (Exception ex)
            {
            }
            return View(cp);
        }

        public ActionResult CityList()
        {
            IList<Location> cities = locationRepository.GetCityListFromCSV();
            return Json(cities, JsonRequestBehavior.AllowGet);
        }

    }
}

CodingExcrcise/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Code Excercise</h1>
    <p class="lead">Click below button to search for city pollution.</p>
    <p><a href="@Url.Action("Index", "Location")" class="btn btn-primary btn-lg">Search &raquo;</a></p>
</div>

CodingExcrcise/Views/Location/Index.cshtml
@model CodingExcrcise.Models.Location

@using (Html.BeginForm("Pollution", "Location", FormMethod.Post, new { @id = "form", onsubmit = "return validateForm();" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Search for Pollution by City: </h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Search by Name", new { @class = "col-md-2" })
        <div class="col-md-2">
            @Html.RadioButton("SearchBy", "Coordinates", false)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <fieldset>

        <div class="form-group">
            @Html.Label("Search by Coordinates", new { @class = "col-md-2" })
            <div class="col-md-2">
                @Html.RadioButton("SearchBy", "Coordinates", true)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coordinate.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coordinate.Latitude, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Coordinate.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coordinate.Longitude, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </fieldset>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Home", "Index")
</div>
@section scripts {
    <script type="text/javascript">
        function validateForm() {
            //check validate if all field are validate true
            if ($('#Coordinate_Latitude').val() == '' ) {
                alert('Please provide latitude');
                $('#Coordinate_Latitude').focus();
                return false;
            }
            if ($('#Coordinate_Longitude').val() == '') {
                alert('Please provide longitude');
                $('#Coordinate_Longitude').focus();
                return false;
            }

            return true;
        }
    </script>
}

CodingExcrcise/Views/Location/Pollution.cshtml
@model CodingExcrcise.Models.Pollution

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pollution</title>
</head>
<body>
    <div>
        <h4>Pollution</h4>
        <hr />

        @if (Model == null) {
    <label class="col-md-2">No record found.</label>
        }
    </div>
    <p>
        @Html.ActionLink("Back to search", "Index")
    </p>
</body>
</html>

CodingExcrcise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
            </div>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>